[build.environment]
  NPM_VERSION = "8.5.0"

[build]
  command = "npm run tinacms && npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]] 
  from = '/api/*' 
  to = '/.netlify/functions/api/:splat' 
  status = 200 