---
new_page_extension: md
auto_deploy: false
admin_path: "/site/static/admin"
webhook_url: 
sections:
- type: document
  path: site/content/_index.md
  label: Home
- type: directory
  path: site/content/team
  label: Team
  create: documents
  match: "**/*"
- type: directory
  path: site/content/offer
  label: Angebot
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - angebotskategorie
  - angebot
- type: directory
  path: site/content/blog
  label: Blog
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-post
- type: document
  path: site/content/contact/_index.md
  label: Kontakt
upload_dir: site/static/upload
public_path: https://yoma-hebammen.ch/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
version: 0.81.0
