baseurl = "/"
languageCode = "de-ch"
languageLang = "de"
title = "Kim und Stefanie"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]

    [[menu.main]]
        identifier = "team"
        name = "Team"
        url = "/" # TODO set correct url
        weight = 100
        [menu.main.params]
            class = "inactive"

    [[menu.main]]
        identifier = "offer"
        name = "Angebot"
        url = "offer"
        weight = 200
        [menu.main.params]
            class = "inactive"

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "blog"
        weight = 300

    [[menu.main]]
        identifier = "contact"
        name = "Kontakt"
        url = "contact"
        weight = 400
        [menu.main.params]
            class = "inactive"
