baseurl = "https://yoma-hebammen.ch"
languageCode = "de-ch"
languageLang = "de"
title = "Yoma Hebammen"

imageCdnBase = "/.netlify/images?url="

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

pluralizeListTitles = false

[menu]

    [[menu.main]]
        identifier = "team"
        name = "Team"
        url = "team"
        weight = 100

    [[menu.main]]
        identifier = "angebot"
        name = "Angebot"
        url = "angebot"
        weight = 200

    [[menu.main]]
        identifier = "feedback"
        name = "Feedback"
        url = "feedback"
        weight = 300

    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "kontakt"
        weight = 400
